FROM gcc:latest

RUN apt-get update && apt-get install -y cmake git

COPY . /usr/src/tests
WORKDIR /usr/src/tests

RUN mkdir build
WORKDIR /usr/src/tests/build

RUN cmake .. && make

# Start server + wait + run tests
CMD sh -c './server 5555 16 1 & sleep 1 && ./runTests'

